#Settings for the application

# Number of threads to use for processing wallets
threads: 1
#Number of retry
retry: 3

#BY DEFAULT: [0,0] - all wallets
#Example: [2, 6] will run wallets 2,3,4,5,6
#[4,4] will run only wallet 4
range_wallets_to_run: [0,0]

# Whether to shuffle the list of wallets before processing
shuffle_wallets: true

# Working only if range_wallet_to_run = [0,0] 
# BY DEFAULT: [] - all wallets 
# Example: [1, 3, 8] - will run only 1, 3 and 8 wallets
exact_wallets_to_run: []

#Check for github updates
check_git_updates: true

# the log level for the application. Options: DEBUG, INFO, WARNING, ERROR
log_level : INFO

# Delay before running the same wallet again after it has completed all actions (1 - 2 hrs default)
random_pause_wallet_after_completion:
  min: 3600
  max: 7200

# Random pause between wallets in seconds
random_pause_between_wallets:
  min: 5
  max: 60

# Random pause between actions in seconds
random_pause_between_actions:
  min: 5
  max: 30

# Random pause between actions in seconds
random_pause_start_wallet:
  min: 0
  max: 60

#Games
games:
  min: 30
  max: 40

#Clicks: !Maximum is 170
clicks:
  min: 60
  max: 154


# Telegram Bot ID for notifications
tg_bot_id: ""

# You can find your chat ID by messaging @userinfobot or using https://web.telegram.org/. (example 1540239116)
tg_user_id: ""

#Maximum possible number of errors before replacement
resources_max_failures: 3
#Perform automatic replacement from proxy reserve files
auto_replace_proxy: True
#Perform automatic replacement from twitter reserve files
auto_replace_twitter: False
